language: cpp
sudo: true
compiler:
  - gcc
  - clang

install:
  # update g++
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90

  # update clang
  - if [ "$CXX" = "clang++" ]; then sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main"; fi
  - if [ "$CXX" = "clang++" ]; then sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-${LLVM_VER} main"; fi
  - if [ "$CXX" = "clang++" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get update -qq; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq clang-${LLVM_VER} llvm-${LLVM_VER}; fi
  - if [ "$CXX" = "clang++" ]; then export CC=clang-${LLVM_VER}; fi
  - if [ "$CXX" = "clang++" ]; then export CXX=clang++-${LLVM_VER}; fi

  # install Qt5
  - sudo add-apt-repository -y ppa:beineri/opt-qt542-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt54base qt54declarative qt54location qt54tools

  # update cmake
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
  - tar xf cmake-3.2.2.tar.gz
  - cd cmake-3.2.2
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j4
  - sudo make install
  - sudo ldconfig
  - cd ../..

script:
  - cmake -DCMAKE_PREFIX_PATH=/opt/qt54/lib/cmake .
  - cmake --build .

branches:
  only:
    - master
    - development

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always

env:
  global:
    - LLVM_VER='3.5'
